name: Deploy to Production

on:
  push:
    branches:
      - master
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
      
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
      
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      
      - name: Build project
        run: pnpm build
      
      - name: Create deployment package
        run: |
          mkdir -p deploy
          cp -r dist deploy/
          cp package.json deploy/
          cp pnpm-lock.yaml deploy/
          cp .env deploy/
          cd deploy
          tar -czf ../deploy.tar.gz .
      
      - name: Deploy to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          source: "deploy.tar.gz"
          target: "/tmp/"
      
      - name: Extract and restart application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd /var/www/chu-tea
            pm2 stop chu-tea || true
            tar -xzf /tmp/deploy.tar.gz -C /var/www/chu-tea
            cd /var/www/chu-tea
            pnpm install --prod --frozen-lockfile
            pm2 restart chu-tea || pm2 start dist/index.js --name chu-tea
            pm2 save
            rm /tmp/deploy.tar.gz
            echo "Deployment completed at $(date )"
